### ISSUE TITLE
Can you change SleekXMPP (dead project) to Slixmpp (Successor)

### ISSUE THREAD

**Issue by Neustradamus** [CRTified/xmppsh#2]
Can you update the code for compatibility with the successor of SleekXMPP?
- https://lab.louiz.org/poezio/slixmpp
- https://github.com/poezio/slixmpp

**Comment by CRTified** [comment]
I'll have a look. Note that this project is more or less orphaned/not used anymore. To be honest, I'd probably rewrite it from scratch when I'm already changing the XMPP library.

**Comment by CRTified** [comment]
I did not rewrite it from scratch (obviously), but it works now with slixmpp as far as I can tell.

**Comment by Neustradamus** [comment]
@CRTified: Perfect, thanks a lot for this quick change :)

Do not forget to update the repository description!

**Comment by CRTified** [comment]
Thanks for the reminder :)
