### ISSUE TITLE
can you help me 

### ISSUE THREAD

**Issue by higher75** [CRTified/xmppsh#3]
Command has been registered: age
DEBUG    Using selector: EpollSelector
DEBUG    Loaded Plugin: RFC 6120: Stream Feature: STARTTLS
DEBUG    Loaded Plugin: RFC 6120: Stream Feature: Resource Binding
DEBUG    Loaded Plugin: RFC 3920: Stream Feature: Start Session
DEBUG    Loaded Plugin: RFC 6121: Stream Feature: Roster Versioning
DEBUG    Loaded Plugin: RFC 6121: Stream Feature: Subscription Pre-Approval
DEBUG    Loaded Plugin: RFC 6120: Stream Feature: SASL
DEBUG    Loaded Plugin: XEP-0030: Service Discovery
DEBUG    Loaded Plugin: XEP-0004: Data Forms
DEBUG    Loaded Plugin: XEP-0045: Multi-User Chat
DEBUG    Event triggered: connecting
DEBUG    DNS: Querying SRV records for ding
DEBUG    DNS: Exception while querying for ding SRV records: (4, 'Domain name not found')
DEBUG    DNS: Querying ding for AAAA records.
DEBUG    DNS: Exception while querying for ding AAAA records: (11, 'Could not contact DNS servers')
DEBUG    DNS: Querying ding for A records.
DEBUG    DNS: Exception while querying for ding A records: (11, 'Could not contact DNS servers')

**Comment by CRTified** [comment]
Your server is not reachable under the given domain. If you configured your DNS records only recently, it might not be propagated. Try connecting with a different XMPP-client first. 

Edit: Also note that `ding` is not a global domain name, but probably only available in your local network
